# Generated by Django 5.0.7 on 2024-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=50)),
                ('menu', models.TextField()),
                ('description', models.TextField()),
                ('header_image', models.ImageField(upload_to='restaurant_headers/')),
                ('logo', models.ImageField(upload_to='restaurant_logos/')),
                ('address', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(max_length=100)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_time', models.CharField(max_length=50)),
                ('branch_status', models.CharField(max_length=50)),
            ],
        ),
    ]
